### ISSUE TITLE
Python: importing other local Python files does not work when running a Python method through UiPath

### ISSUE THREAD

**Issue by andumorie** [UiPath/Community.Activities#43]
**Describe the bug**
If you import a function from another Python file and use the Load Script activity, UiPath throws this exception: "ModuleNotFoundError : No module named 'to_import'"

**To Reproduce**
1. Create a Python file that imports and calls a function from another local Python file
2. Running that Python script through the command line works as expected
3. Running that same Python script through UiPath Load Script gives the above exception

**Expected behavior**
It should import the function and run it without any problem, just like from the command line.

**Additional context**
Example workflow here: https://drive.google.com/open?id=110ZaUyYRcYuUv5y6pvP0SKO8OcLgo2bw

**Comment by Krogsager** [comment]
Seconded. I made a post at https://forum.uipath.com/t/python-source-file-cannot-be-found/105883
but was directed to post here on github.

**Comment by andumorie** [comment]
This issue was fixed in package version 1.0.7053.27728 with the addition of the Working Folder property of the Python Scope activity. Setting the Working Folder property to the current directory now allows other local Python files/modules to be imported.

**Comment by tg970** [comment]
Hi @andumorie - I'm running the package version 1.1.6863.33404 the 'WorkingFolder' input property has disappeared from the Python Scope activity. When I downgraded to the 1.0.7053.27728 version, it's there. Any idea why, or how, that addition was missed in the version bump?

Thanks!
