### ISSUE TITLE
FTP: File Exist Activity returns false

### ISSUE THREAD

**Issue by andresm9** [UiPath/Community.Activities#46]
**Describe the bug**
File Exist Activity doesn't return true if file exist in folder (Using FullPath)

**To Reproduce**
1. Start FTP Connection
2. Add "File Exists" activity and a valid fullpath
3. See error

**Expected behavior**
return True if file exist, false if not

**Screenshots**
![image](https://user-images.githubusercontent.com/14965388/52821348-89f31d00-307c-11e9-9f39-f60a84c29deb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Package Version: UiPath.FTP.Activities 1.0.6710.16240

**Additional context**
Possibly issues on FluentFTP Depencendy Library

**Comment by gajendragajay** [comment]
This issue is no more encountered. Hence, activity working fine. Please Close this issue.

**Comment by theloginerror** [comment]
I tested it on the latest version of UiPath.FTP.Activities 1.0.7346.28183 and it is indeed working as expected.
@cosmyo Let's close this one.
